language: php
php:
  - 7.2

before_script:
  # Set up Composer.
  - composer selfupdate --no-interaction
  - composer config -l
  - composer clear-cache

  # Use 'composer create-project' to create our SUT
  - |
    echo "{ \"package\": { \"name\": \"greg-1-anderson/drupal-drupal-composer\", \"version\": \"1.0.0\", \"source\": { \"url\": \"$(pwd)/.git\", \"type\": \"git\", \"reference\": \"master\" } } }" > /tmp/packages.json
  - composer create-project --repository-url=/tmp/packages.json greg-1-anderson/drupal-drupal-composer /tmp/drupal-drupal-composer
  - composer --working-dir=/tmp/drupal-drupal-composer composer:scaffold

  # Look up the version of drupal/core in our SUT, and use it to download a tarball
  - |
    DRUPAL_CORE_VERSION=$(composer --working-dir=/tmp/drupal-drupal-composer show drupal/core | grep 'versions' | grep -o -E '\*\ .+' | cut -d' ' -f2 | cut -d',' -f1;)
    echo "Drupal core version is $DRUPAL_CORE_VERSION"
    curl -o /tmp/drupal.tgz https://ftp.drupal.org/files/projects/drupal-$DRUPAL_CORE_VERSION.tar.gz
    ls /tmp
    cd /tmp
    tar -xzvf drupal.tgz >/dev/null
    mv drupal-$DRUPAL_CORE_VERSION drupal-untarred

  # Repair the tarball:
  #  - Remove info from drupal.org packaging from info.yml files
  #  - Remove the "composer" directory
  - find /tmp/drupal-untarred -name "*.info.yml" -exec sed -e 's/^# version:/version:/' -e 's/^# core:/core:/' -e '/# Information added by Drupal.org packaging script/,$d' -i {} \;
  - rm -rf /tmp/drupal-untarred/composer

  # Repair the SUT:
  #  - Remove the README.md and the scaffold files
  - rm /tmp/drupal-drupal-composer/README.md
  - rm -rf /tmp/drupal-drupal-composer/core/assets/scaffold

  # Extra files that exist in the SUT that are not present in the tarball.
  # Not sure why some of these are present, but these are not significant, so
  # it does not matter.
  - rm -rf /tmp/drupal-drupal-composer/vendor/behat/mink/CONTRIBUTING.md
  - rm -rf /tmp/drupal-drupal-composer/vendor/behat/mink/.git
  - rm -rf /tmp/drupal-drupal-composer/vendor/behat/mink/.gitattributes
  - rm -rf /tmp/drupal-drupal-composer/vendor/behat/mink/.gitignore
  - rm -rf /tmp/drupal-drupal-composer/vendor/behat/mink/phpdoc.ini.dist
  - rm -rf /tmp/drupal-drupal-composer/vendor/behat/mink/phpunit.xml.dist
  - rm -rf /tmp/drupal-drupal-composer/vendor/behat/mink/.travis.yml
  - rm -rf /tmp/drupal-drupal-composer/vendor/behat/mink-selenium2-driver/.git
  - rm -rf /tmp/drupal-drupal-composer/vendor/easyrdf/easyrdf/scripts
  - rm -rf /tmp/drupal-drupal-composer/vendor/jcalderonzumba/gastonjs/docs
  - rm -rf /tmp/drupal-drupal-composer/vendor/jcalderonzumba/gastonjs/examples
  - rm -rf /tmp/drupal-drupal-composer/vendor/justinrainbow/json-schema/demo
  - rm -rf /tmp/drupal-drupal-composer/vendor/masterminds/html5/bin
  - rm -rf /tmp/drupal-drupal-composer/vendor/pear/archive_tar/docs
  - rm -rf /tmp/drupal-drupal-composer/vendor/phar-io/manifest/examples
  - rm -rf /tmp/drupal-drupal-composer/vendor/phpspec/prophecy/fixtures
  - rm -rf /tmp/drupal-drupal-composer/vendor/phpspec/prophecy/spec

script:
  # Check for differences between the tarball and the SUT (except vendor)
  - |
    diff -rBq \
    -x vendor \
    -x autoload.php \
    -x test \
    -x Test \
    -x tests \
    -x Tests \
    -x .git \
    -x .travis.yml \
    -x .gitignore \
    -x LICENSE.txt \
    -x composer.json \
    -x composer.lock \
    /tmp/drupal-untarred /tmp/drupal-drupal-composer
  # Check for differences between the vendor directory in the tarball and the SUT
  - |
    diff -rBq \
    -x .htaccess \
    -x autoload.php \
    -x test \
    -x Test \
    -x tests \
    -x Tests \
    -x web.config \
    -x composer \
    -x doc \
    -x ext \
    -x Resources \
    -x drupal \
    /tmp/drupal-untarred/vendor /tmp/drupal-drupal-composer/vendor
