language: php
php:
  - 7.2

before_script:
  # Set up Composer.
  - composer selfupdate --no-interaction
  - composer config -l
  - composer clear-cache

script:
  # Run our test script
  - ./test.sh /tmp
